export const SET_PLACES = 'SET_PLACES';

export const GET_WHETHER_DATA = 'GET_WHETHER_DATA';
export const GET_WHETHER_DATA_RECEIVED = 'GET_WHETHER_DATA_RECEIVED';
export const GET_WHETHER_DATA_ERROR = 'GET_WHETHER_DATA_ERROR';
